export default {
  vendorList: [
    { value: 'AQM', label: 'AQM' },
    { value: 'TCS', label: 'TCS' },
    { value: 'HoneyBee', label: 'HoneyBee' },
    { value: 'Harjai', label: 'Harjai' },
    {
      value: 'PINNACLE TECHNOLOGY CONSULTANCY SERVICES PVT LTD',
      label: 'PINNACLE TECHNOLOGY CONSULTANCY SERVICES PVT LTD',
    },
    { value: 'FA Software Services Pvt Ltd', label: 'FA Software Services Pvt Ltd' },
    { value: 'Clover Infotech', label: 'Clover Infotech' },
    { value: 'TCS SI', label: 'TCS SI' },
    { value: 'Precision Tech Ltd', label: 'Precision Tech Ltd' },
    { value: 'Predoole', label: 'Predoole' },
    { value: 'Technosicion', label: 'Technosicion' },
    { value: 'FluidLive', label: 'FluidLive' },
    { value: 'Apmosys', label: 'Apmosys' },
  ],

  timesheetEmpList: [
    {
        "id": 46,
        "employeeId": "CI15413",
        "partnerName": "Clover Infotech",
        "employeeFirstName": "Atharva Pradeep",
        "employeeLastName": "Khatu",
        "employeeFullName": "Atharva Pradeep Khatu",
        "employeeStatus": "Active",
        "officialEmail": "na@na.com",
        "personalEmail": "test@test.com",
        "mobileNumber": "9999999999",
        "whatsappNumber": "8888888888",
        "joiningDate": "2022-06-01",
        "reportingTeamLead": "ravi.kumar044@bajajallianz.co.in",
        "reportingManager": "mandar.pathak@bajajallianz.co.in",
        "reportingItSpoc": "pooja.rebba@bajajallianz.co.in",
        "billingSlab": "0",
        "designation": null,
        "skillSet": null,
        "evaluationPeriod": null,
        "createdBy": "SYSTEM",
        "newReplacement": null,
        "replacementEcode": null,
        "supportDevelopment": "Project - MAXIMUS",
        "reportingAvpVpSvp": "mandar.pathak@bajajallianz.co.in",
        "verticalHeadHod": "Avinash Naik",
        "functionDesc": "Development",
        "departmentDesc": "IT",
        "verticalMain": "IT",
        "verticalSub": "IT-All IT Departments",
        "projectType": "Project - Maximus Motor",
        "maximusOpus": "",
        "invoiceType": "CapEx",
        "createdOn": "2023-11-06T18:30:00.000+00:00",
        "updatedOn": "2023-10-31T18:30:00.000+00:00",
        "errorCode": null,
        "errorDesc": null,
        "tlApprovalFlag": null,
        "smApprovalFlag": null,
        "itSpocFlag": null,
        "remarks": null,
        "dateOfBirth": null,
        "gender": null,
        "experience": null,
        "totalExperience": null,
        "lob": null,
        "resignationDate": null,
        "lwd": null,
        "webId": 'atharva.khatu@its.bajajallianz.co.in',
    },
    {
        "id": 213,
        "employeeId": "CI15462",
        "partnerName": "Clover Infotech",
        "employeeFirstName": "Sagar",
        "employeeLastName": "Shelar",
        "employeeFullName": "Sagar Shelar",
        "employeeStatus": "Active",
        "officialEmail": "na@na.com",
        "personalEmail": "test@test.com",
        "mobileNumber": "9999999999",
        "whatsappNumber": "8888888888",
        "joiningDate": "2023-06-19",
        "reportingTeamLead": "mandar.pathak@bajajallianz.co.in",
        "reportingManager": "mandar.pathak@bajajallianz.co.in",
        "reportingItSpoc": "pooja.rebba@bajajallianz.co.in",
        "billingSlab": "0",
        "designation": null,
        "skillSet": null,
        "evaluationPeriod": null,
        "createdBy": "SYSTEM",
        "newReplacement": null,
        "replacementEcode": null,
        "supportDevelopment": "UI/UX",
        "reportingAvpVpSvp": "mandar.pathak@bajajallianz.co.in",
        "verticalHeadHod": "Avinash Naik",
        "functionDesc": "Development",
        "departmentDesc": "IT",
        "verticalMain": "IT",
        "verticalSub": "IT-All IT Departments",
        "projectType": "RUN",
        "maximusOpus": "Male",
        "invoiceType": "OpEx",
        "createdOn": "2023-11-06T18:30:00.000+00:00",
        "updatedOn": "2023-10-31T18:30:00.000+00:00",
        "errorCode": null,
        "errorDesc": null,
        "tlApprovalFlag": null,
        "smApprovalFlag": null,
        "itSpocFlag": null,
        "remarks": null,
        "dateOfBirth": null,
        "gender": null,
        "experience": null,
        "totalExperience": null,
        "lob": null,
        "resignationDate": null,
        "lwd": null,
        "webId": 'sagar.arunshelar@its.bajajallianz.co.in'
    },
    {
        "id": 48,
        "employeeId": "CI15132",
        "partnerName": "Clover Infotech",
        "employeeFirstName": "Ayush",
        "employeeLastName": "Chinchane",
        "employeeFullName": "Ayush Chinchane",
        "employeeStatus": "Active",
        "officialEmail": "na@na.com",
        "personalEmail": "test@test.com",
        "mobileNumber": "9999999999",
        "whatsappNumber": "8888888888",
        "joiningDate": "2023-04-03",
        "reportingTeamLead": "saratham.am@bajajallianz.co.in",
        "reportingManager": "mandar.pathak@bajajallianz.co.in",
        "reportingItSpoc": "pooja.rebba@bajajallianz.co.in",
        "billingSlab": "0",
        "designation": null,
        "skillSet": null,
        "evaluationPeriod": null,
        "createdBy": "SYSTEM",
        "newReplacement": null,
        "replacementEcode": null,
        "supportDevelopment": "ITSM",
        "reportingAvpVpSvp": "mandar.pathak@bajajallianz.co.in",
        "verticalHeadHod": "Ramandeep Sahni",
        "functionDesc": "Development",
        "departmentDesc": null,
        "verticalMain": "Finance & Accounts",
        "verticalSub": "Finance-Accounts",
        "projectType": "RUN",
        "maximusOpus": "",
        "invoiceType": "OpEx",
        "createdOn": "2023-11-06T18:30:00.000+00:00",
        "updatedOn": "2023-10-31T18:30:00.000+00:00",
        "errorCode": null,
        "errorDesc": null,
        "tlApprovalFlag": null,
        "smApprovalFlag": null,
        "itSpocFlag": null,
        "remarks": null,
        "dateOfBirth": null,
        "gender": null,
        "experience": null,
        "totalExperience": null,
        "lob": null,
        "resignationDate": null,
        "lwd": null,
        "webId": 'ayush.chinchane01@its.bajajallianz.co.in',
    },
]
};
