export default {
  vendorList: [
    { value: 'AQM', label: 'AQM' },
    { value: 'TCS', label: 'TCS' },
    { value: 'HoneyBee', label: 'HoneyBee' },
    { value: 'Harjai', label: 'Harjai' },
    {
      value: 'PINNACLE TECHNOLOGY CONSULTANCY SERVICES PVT LTD',
      label: 'PINNACLE TECHNOLOGY CONSULTANCY SERVICES PVT LTD',
    },
    { value: 'FA Software Services Pvt Ltd', label: 'FA Software Services Pvt Ltd' },
    { value: 'Clover Infotech', label: 'Clover Infotech' },
    { value: 'TCS SI', label: 'TCS SI' },
    { value: 'Precision Tech Ltd', label: 'Precision Tech Ltd' },
    { value: 'Predoole', label: 'Predoole' },
    { value: 'Technosicion', label: 'Technosicion' },
    { value: 'FluidLive', label: 'FluidLive' },
    { value: 'Apmosys', label: 'Apmosys' },
    { value: 'Lumiq', label: 'Lumiq' },
  ],

  timesheetEmpList: [
    {
      id: 46,
      employeeId: 'CI15413',
      partnerName: 'Clover Infotech',
      employeeFirstName: 'Atharva Pradeep',
      employeeLastName: 'Khatu',
      employeeFullName: 'Atharva Pradeep Khatu',
      employeeStatus: 'Active',
      officialEmail: 'na@na.com',
      personalEmail: 'test@test.com',
      mobileNumber: '9999999999',
      whatsappNumber: '8888888888',
      joiningDate: '2022-06-01',
      reportingTeamLead: 'ravi.kumar044@bajajallianz.co.in',
      reportingManager: 'mandar.pathak@bajajallianz.co.in',
      reportingItSpoc: 'pooja.rebba@bajajallianz.co.in',
      billingSlab: '0',
      designation: null,
      skillSet: null,
      evaluationPeriod: null,
      createdBy: 'SYSTEM',
      newReplacement: null,
      replacementEcode: null,
      supportDevelopment: 'Project - MAXIMUS',
      reportingAvpVpSvp: 'mandar.pathak@bajajallianz.co.in',
      verticalHeadHod: 'Avinash Naik',
      functionDesc: 'Development',
      departmentDesc: 'IT',
      verticalMain: 'IT',
      verticalSub: 'IT-All IT Departments',
      projectType: 'Project - Maximus Motor',
      maximusOpus: '',
      invoiceType: 'CapEx',
      createdOn: '2023-11-06T18:30:00.000+00:00',
      updatedOn: '2023-10-31T18:30:00.000+00:00',
      errorCode: null,
      errorDesc: null,
      tlApprovalFlag: null,
      smApprovalFlag: null,
      itSpocFlag: null,
      remarks: null,
      dateOfBirth: null,
      gender: null,
      experience: null,
      totalExperience: null,
      lob: null,
      resignationDate: null,
      lwd: null,
      webId: 'atharva.khatu@its.bajajallianz.co.in',
    },
    {
      id: 213,
      employeeId: 'CI15462',
      partnerName: 'Clover Infotech',
      employeeFirstName: 'Sagar',
      employeeLastName: 'Shelar',
      employeeFullName: 'Sagar Shelar',
      employeeStatus: 'Active',
      officialEmail: 'na@na.com',
      personalEmail: 'test@test.com',
      mobileNumber: '9999999999',
      whatsappNumber: '8888888888',
      joiningDate: '2023-06-19',
      reportingTeamLead: 'mandar.pathak@bajajallianz.co.in',
      reportingManager: 'mandar.pathak@bajajallianz.co.in',
      reportingItSpoc: 'pooja.rebba@bajajallianz.co.in',
      billingSlab: '0',
      designation: null,
      skillSet: null,
      evaluationPeriod: null,
      createdBy: 'SYSTEM',
      newReplacement: null,
      replacementEcode: null,
      supportDevelopment: 'UI/UX',
      reportingAvpVpSvp: 'mandar.pathak@bajajallianz.co.in',
      verticalHeadHod: 'Avinash Naik',
      functionDesc: 'Development',
      departmentDesc: 'IT',
      verticalMain: 'IT',
      verticalSub: 'IT-All IT Departments',
      projectType: 'RUN',
      maximusOpus: 'Male',
      invoiceType: 'OpEx',
      createdOn: '2023-11-06T18:30:00.000+00:00',
      updatedOn: '2023-10-31T18:30:00.000+00:00',
      errorCode: null,
      errorDesc: null,
      tlApprovalFlag: null,
      smApprovalFlag: null,
      itSpocFlag: null,
      remarks: null,
      dateOfBirth: null,
      gender: null,
      experience: null,
      totalExperience: null,
      lob: null,
      resignationDate: null,
      lwd: null,
      webId: 'sagar.arunshelar@its.bajajallianz.co.in',
    },
    {
      id: 48,
      employeeId: 'CI15132',
      partnerName: 'Clover Infotech',
      employeeFirstName: 'Ayush',
      employeeLastName: 'Chinchane',
      employeeFullName: 'Ayush Chinchane',
      employeeStatus: 'Active',
      officialEmail: 'na@na.com',
      personalEmail: 'test@test.com',
      mobileNumber: '9999999999',
      whatsappNumber: '8888888888',
      joiningDate: '2023-04-03',
      reportingTeamLead: 'saratham.am@bajajallianz.co.in',
      reportingManager: 'mandar.pathak@bajajallianz.co.in',
      reportingItSpoc: 'pooja.rebba@bajajallianz.co.in',
      billingSlab: '0',
      designation: null,
      skillSet: null,
      evaluationPeriod: null,
      createdBy: 'SYSTEM',
      newReplacement: null,
      replacementEcode: null,
      supportDevelopment: 'ITSM',
      reportingAvpVpSvp: 'mandar.pathak@bajajallianz.co.in',
      verticalHeadHod: 'Ramandeep Sahni',
      functionDesc: 'Development',
      departmentDesc: null,
      verticalMain: 'Finance & Accounts',
      verticalSub: 'Finance-Accounts',
      projectType: 'RUN',
      maximusOpus: '',
      invoiceType: 'OpEx',
      createdOn: '2023-11-06T18:30:00.000+00:00',
      updatedOn: '2023-10-31T18:30:00.000+00:00',
      errorCode: null,
      errorDesc: null,
      tlApprovalFlag: null,
      smApprovalFlag: null,
      itSpocFlag: null,
      remarks: null,
      dateOfBirth: null,
      gender: null,
      experience: null,
      totalExperience: null,
      lob: null,
      resignationDate: null,
      lwd: null,
      webId: 'ayush.chinchane01@its.bajajallianz.co.in',
    },
  ],

  evaluationPeriodList: [
    {
      value: '0 Days',
      label: '0 Days',
    },
    {
      value: '15 Days',
      label: '15 Days',
    },
    {
      value: '30 Days',
      label: '30 Days',
    },
    {
      value: '45 Days',
      label: '45 Days',
    },
    {
      value: '60 Days',
      label: '60 Days',
    },
  ],

  newReplacementList: [
    {
      value: 'New',
      label: 'New',
    },
    {
      value: 'Replacement',
      label: 'Replacement',
    },
  ],

  supportDevelopmentList: [
    {
      value: 'Support',
      label: 'Support',
    },
    {
      value: 'Development',
      label: 'Development',
    },
    {
      value: 'Testing',
      label: 'Testing',
    },
    {
      value: 'MIS',
      label: 'MIS',
    },
    {
      value: 'Project',
      label: 'Project',
    },
    {
      value: 'Infra Support',
      label: 'Infra Support',
    },
  ],

  employeeStatusList: [
    {
      value: 'Active',
      label: 'Active',
    },
    {
      value: 'Resigned',
      label: 'Resigned',
    },
  ],

  genderList: [
    {
      value: 'Male',
      label: 'Male',
    },
    {
      value: 'Female',
      label: 'Female',
    },
  ],

  experienceSlab: [
    {
      value: '0 - 2 years',
      label: '0 - 2 years',
    },
    {
      value: '2 - 4 years',
      label: '2 - 4 years',
    },
    {
      value: '4 - 6 years',
      label: '4 - 6 years',
    },
    {
      value: '6 - 8 years',
      label: '6 - 8 years',
    },
    {
      value: '8 - 10 years',
      label: '8 - 10 years',
    },
    {
      value: '10 years and above',
      label: '10 years and above',
    },
  ],

  LOBList: [
    {
      value: 'Health',
      label: 'Health',
    },
    {
      value: 'Motor OD',
      label: 'Motor OD',
    },
    {
      value: 'Motor TP',
      label: 'Motor TP',
    },
    {
      value: 'Non-motor',
      label: 'Non-motor',
    },
    {
      value: 'Travel',
      label: 'Travel',
    },
    {
      value: 'PG',
      label: 'PG',
    },
    {
      value: 'DBA',
      label: 'DBA',
    },
    {
      value: 'Testing',
      label: 'Testing',
    },

    {
      value: 'MIS',
      label: 'MIS',
    },
    {
      value: 'Accounting',
      label: 'Accounting',
    },
    {
      value: 'Customer Support',
      label: 'Customer Support',
    },
    {
      value: 'Infra',
      label: 'Infra',
    },
  ],
  maximusOpusList: [
    {
      value: 'Maximus',
      label: 'Maximus',
    },
    {
      value: 'Opus',
      label: 'Opus',
    },
    {
      value: 'Infra',
      label: 'Infra',
    },
  ],

  designationList: [
    { value: 'Software Engineer', label: 'Software Engineer' },
    { value: 'IT Support', label: 'IT Support' },
    { value: 'Software Developer', label: 'Software Developer' },
    { value: 'Fuctional Tester', label: 'Fuctional Tester' },
    { value: 'Test Engineer', label: 'Test Engineer' },
    { value: 'Systems Support Lead', label: 'Systems Support Lead' },
    { value: 'Developer', label: 'Developer' },
    { value: 'QA Engineer', label: 'QA Engineer' },
    { value: 'Security Tester', label: 'Security Tester' },
    { value: 'Technical Associate', label: 'Technical Associate' },
    { value: 'Project Engineer', label: 'Project Engineer' },
    { value: 'System Engineer', label: 'System Engineer' },
    { value: 'Project Leader', label: 'Project Leader' },
    { value: 'Senior Software Engineer', label: 'Senior Software Engineer' },
    { value: 'IT Engineer', label: 'IT Engineer' },
    { value: 'Senior Developer', label: 'Senior Developer' },
    { value: 'Systems Support Engineer', label: 'Systems Support Engineer' },
    { value: 'Programmer', label: 'Programmer' },
    { value: 'Technical Lead', label: 'Technical Lead' },
    { value: 'Senior Programmer', label: 'Senior Programmer' },
    { value: 'L2 Support', label: 'L2 Support' },
    { value: 'L3 Support', label: 'L3 Support' },
    { value: 'Seniour Software Engineer', label: 'Seniour Software Engineer' },
    { value: 'Team Leader', label: 'Team Leader' },
    { value: 'L2 Application Support Engineer', label: 'L2 Application Support Engineer' },
    { value: 'Data Engineer', label: 'Data Engineer' },
    { value: 'Application Support', label: 'Application Support' },
    { value: 'Perfomance Tester', label: 'Perfomance Tester' },
    { value: 'Network Administrator', label: 'Network Administrator' },
    { value: 'Technical Engineer', label: 'Technical Engineer' },
    { value: 'Cloud Engineer', label: 'Cloud Engineer' },
    { value: 'Engineer', label: 'Engineer' },
    { value: 'MIS Executive', label: 'MIS Executive' },
    { value: 'Security Consultant', label: 'Security Consultant' },
    { value: 'Junior Developer', label: 'Junior Developer' },
    { value: 'Senior Software Developer', label: 'Senior Software Developer' },
    { value: 'Automation Test Engineer', label: 'Automation Test Engineer' },
  ],
  invoiceTypeList: [
    {
      value: 'CapEx',
      label: 'CapEx',
    },
    {
      value: 'OpEx',
      label: 'OpEx',
    },
  ],
};
